config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'recipes#index'


resources :recipes, only: [:index, :show, :new, :update, :destroy, :create] do
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
end

resources :foods do
  resources :recipe_foods, only: %i[edit, update, new, create, index, destroy]
end

get 'general_shopping_list/:recipe_id', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

resources :recipe_food, only: %i[index show edit update destroy]
resources :public_recipes, only: %i[index show]

resources :shopping_list, only: %i[index show]
resources :general_shopping_list, only: %i[index show]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 500 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  include RecipesHelper

  def index
    @recipes = current_user.recipes.includes(:recipe_foods)
    flash.delete(:notice) unless request.referrer == new_recipe_url
  end

  def show
    notice_message
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    render :show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    @recipe.public = params[:public] == 'Public'

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update recipe_params

    @recipe.public = params[:public] == 'Public'

    @recipe.save
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if can? :destroy, @recipe
        @recipe.destroy
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to recipes_path, alert: 'Recipe was not deleted.' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_public
    @recipe = current_user.recipes.find_by(id: params[:id])
    @recipe&.update(public: !@recipe.public)
    redirect_to request.referrer || root_path
  end

  def general_shopping_list
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_id = params[:recipe_id]
    @user = current_user
    recipe_foods = @recipe.recipe_foods.includes(food: :user)
    user_foods = @user.foods

    @missing_foods = []

    recipe_foods.each do |recipe_food|
      user_food = user_foods.find_by(name: recipe_food.food.name)

      next unless user_food.nil? || user_food.quantity < recipe_food.quantity

      quantity_needed = recipe_food.quantity - (user_food&.quantity || 0)

      total_price_needed = quantity_needed * recipe_food.food.price

      @missing_foods << {
        food_name: recipe_food.food.name,
        quantity_needed:,
        price_per_unit: recipe_food.food.price,
        total_price_needed:
      }
    end

    @total_value_needed = @missing_foods.sum { |missing_food| missing_food[:total_price_needed] }
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def notice_message
    url = Rails.application.routes.recognize_path(request.referrer)
    flash.delete(:notice) unless %w[index show new edit update
                                    destroy].include?(url[:action]) && url[:controller] == 'recipes'
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, url: recipes_path, local: true) do |form| %>
  <div class = "mt-4 p-2">
    <%= select_tag(:public, options_for_select([['Select Status', 'Status'], ['Public', 'Public'], ['Private', 'Private']], 'Status'),
      class: 'form-select')
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:status].first %>
        </p>
    <% end %>
  </div>

	<div class = "mt-2 p-2">
		<%= form.text_field :name,
        autofocus: true, 
        autocomplete: 'name', 
        placeholder: 'New recipe name', 
        class: 'form-control' 
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:name].first %>
        </p>
    <% end %>
	</div>

  <div class = "mt-2 p-2">
    <%= form.number_field :preparation_time,
        autofocus: true,
        autocomplete: 'preparation_time',
        placeholder: 'Preparation time in hour(s)',
        class: 'form-control'
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:preparation_time].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.number_field :cooking_time,
        autofocus: true,
        autocomplete: 'cooking_time',
        placeholder: 'Cooking time in hour(s)',
        class: 'form-control'
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:cooking_time].first %>
        </p>
    <% end %>
  </div>

	<div class = "mt-2 p-2">
		<%= form.text_area :description, rows: "5",
        autofocus: true, 
        autocomplete: 'description', 
        placeholder: 'Description of the recipe', 
        class: 'form-control' 
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:description].first %>
        </p>
    <% end %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: 'btn btn-outline-dark btn-sm mt-4' %>
    <%= link_to 'Cancel', recipes_path, class: 'btn btn-outline-dark btn-sm mt-4 px-3' %>
  </div>
<% end %>

app/views/recipes/general_shopping_list.html.erb
     <h2>Shopping List</h2>
<div class = "shopping_list_container">

<div class = "shopping_list_wrapper">
<div>
<h5>Amount of food to buy: <%= @missing_foods.length%> </h5>
</div>
<div>
<h5>Total value of food needed: $<%= @total_value_needed %> </h5>
</div>
</div>
	<table class="table table-striped table-bordered table-size">
					<thead>
						<tr>
							<th scope="col">Food</th>
							<th scope="col">Quantity</th>
							<th scope="col">Price</th>
						</tr>
					</thead>
					<tbody>
				 <% @missing_foods.each do |missing_food| %>	
         	<tr>
									
							<td><%= missing_food[:food_name] %></td>
                             <td><%= missing_food[:quantity_needed] %></td>
				
						 <td>$<%= missing_food[:total_price_needed] %></td>
			
								<% end %>

						</tr>
					</tbody>
			</table>

            </div>
            </div>
            </div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container recipe-form">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 mt-4 p-2">
      <h1 class="text-center">
        Recipes List
      </h1>
    
      <div class="d-flex justify-content-end p-2">
        <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-primary text-right" %>
      </div>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
        </p>
      <% elsif @recipes.empty? %>
        <p class="alert alert-info">
          No recipes added yet. Please add new recipe.
        </p>
      <% end %>

     
        <% @recipes.each do |recipe| %>
          <div class="row border mb-4">
            <div class="col-4 p-2 text-start">
              <%= link_to recipe.name, recipe_path(recipe), class: 'nav-link mb-3 fs-4 link-dark'%>
            
                <%= button_to "Remove", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: 'btn btn-danger mx-3 fs-5 p-1 custom-button-width' %>
        
              </div>
            <div class="col p-2 text-start">
              <p><%= recipe.description %></p>
            </div>
          </div>
        <% end %>
   
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-4 p-2">
      <h1 class="text-center">New Recipe</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8 mt-4 p-2">
      <h1 class="text-center">
        <%= @recipe.name %>
      </h1>
  
      <div class="d-flex justify-content-between align-items-center mb-3">
        <span>
          Preparation Time:
          <%= @recipe.preparation_time %>
          <%= @recipe.preparation_time > 1 ? 'hours' : 'hour' %> 
        </span>
   <%= form_with(model: @recipe, url: toggle_public_path(@recipe), method: :patch) do |form| %>
  <div class="form-check form-switch form-check-reverse">
  <%= form.check_box :public, { class: 'form-check-input', id: 'flexSwitchCheckReverse' } %>
  <label class="form-check-label" for="flexSwitchCheckReverse">Public</label>
  </div>
  <%= form.submit 'Toggle Public', class: 'btn btn-primary' %>
<% end %>

      </div>

      <span class="d-block mb-3">
        Cooking Time:
        <%= @recipe.cooking_time %>
        <%= @recipe.cooking_time > 1 ? 'hours' : 'hour' %>
      </span>
      <span class="steps">Steps goes here...</span>

      <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="add-btn">
          <%= link_to 'Generate shopping list', general_shopping_list_path(recipe_id: @recipe.id), class: 'btn btn-secondary' %>
        </div>

        <div class="add-btn">
          <%= link_to 'Add ingredient', new_recipe_recipe_food_path(recipe_id: @recipe.id), class: 'btn btn-primary' %>
        </div>
      </div>

      <hr/>
      <% if @recipe.recipe_foods.empty? %>
        <p class="no-record text-center">
          No food ingredient added to this recipe yet.
        </p>
      <% end %>

      <% if @recipe.recipe_foods.any? %>
        <table class="table table-striped table-bordered mt-2">
					<thead>
						<tr>
						  <th scope="col">#</th>
							<th scope="col">Food</th>
							<th scope="col">Quantity</th>
							<th scope="col">Value</th>
							<th scope="col" class="text-center">Actions</th>
						</tr>
					</thead>
					<tbody>
            <% @recipe.recipe_foods.each_with_index do |food_recipe, index| %>
              <tr>
                <td><%= index + 1 %></td>										
                <td><%=food_recipe.food.name %></td>
                <td>
                  <%= food_recipe.quantity%>
                  <%= food_recipe.food.measurement_unit %>
                </td>
                <td>
                  <% if food_recipe.quantity.present? && food_recipe.food.price.present? %>
                      <%= food_recipe.quantity * food_recipe.food.price %>
                  <% else %>
                    N/A
                  <% end %>
                </td>
                <td class="d-flex justify-content-center justify-content-around">
                  <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, food_recipe), class: 'btn btn-danger btn-sm' %>
                  <%= form_with(url: recipe_recipe_food_path(@recipe, food_recipe), method: :delete, data: { confirm: 'Are you sure?' }) do |f| %>
                    <%= f.submit 'Remove', class: 'btn btn-danger btn-sm' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
			  </table>
      <% end %>
    </div>
  </div>
</div>