config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'recipes#index'


resources :recipes, only: [:index, :show, :new, :update, :destroy, :create] do
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
end

resources :foods do
  resources :recipe_foods, only: %i[edit, update, new, create, index, destroy]
end

get 'general_shopping_list/:recipe_id', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

resources :recipe_food, only: %i[index show edit update destroy]
resources :public_recipes, only: %i[index show]

resources :shopping_list, only: %i[index show]
resources :general_shopping_list, only: %i[index show]
end

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'RecipeApp', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-right" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          
          <li class="nav-item">
            <% if current_page?(foods_path) %>
              <%= link_to "New Food", new_food_path, class: "nav-link" %>
            <% else %>
              <%= link_to "Foods", foods_path, class: "nav-link" %>
            <% end %>
          </li>

          <li class="nav-item">
            <% if current_page?(recipes_path) %>
              <%= link_to "New Recipe", new_recipe_path, class: "nav-link" %>
            <% else %>
              <%= link_to "Recipes", recipes_path, class: "nav-link" %>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, form_class: "nav-link" %>
          </li> %>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_recipe.html.erb
<div class = "form-wrapper">
<%= form_with(model: @recipe, url:(recipes_path), local: true)  do |f| %>
<div>
  <%= f.label :name%><br>
  <%= f.text_field :name,  class: "form-title" %>
</div>
<div>
  <%= f.label :description %><br>
  <%= f.text_area :description, class: "form-text" %>
</div>
<div>
  <%= f.label :preparation_time %><br>
  <%= f.text_field :preparation_time, class: "form-text" %>
</div>
<div>
  <%= f.label :cooking_time %><br>
  <%= f.text_field :cooking_time, class: "form-text" %>
</div>
<div>
  <%= f.label :public %><br>
  <%= f.check_box :public, class: "form-checkbox" %>
</div>
<div>
<%=f.submit class: "form-btn"%>
</div>
<% end %>
</div>