config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'recipes#index'


resources :recipes, only: [:index, :show, :new, :update, :destroy, :create] do
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
end

resources :foods do
  resources :recipe_foods, only: %i[edit, update, new, create, index, destroy]
end

get 'general_shopping_list/:recipe_id', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

resources :recipe_food, only: %i[index show edit update destroy]
resources :public_recipes, only: %i[index show]

resources :shopping_list, only: %i[index show]
resources :general_shopping_list, only: %i[index show]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :user_id },
                   length: { minimum: 3, maximum: 50 }
  validates :measurement_unit, presence: true, length: { minimum: 2, maximum: 10 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0, decimal: true, precision: 8, scale: 2 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  include FoodsHelper

  def index
    notice_message
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def edit
    @food = Food.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: @food }
    end
  end

  def update
    @food = Food.find(params[:id])
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to foods_path, notice: 'Food was successfully updated.' }
        format.json { render :index, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :index, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    respond_to do |format|
      if @food.destroy
        format.html { redirect_to foods_path, notice: 'Food was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html do
          redirect_to foods_path,
                      alert: 'The food was added to either recipe or inventory and could not be destroyed.'
        end
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.fetch(:food, {}).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
  def notice_message
    url = Rails.application.routes.recognize_path(request.referrer)
    flash.delete(:notice) unless %w[index show new edit update
                                    destroy].include?(url[:action]) && url[:controller] == 'recipes'
  end
end

app/views/foods/_form.html.erb
 <%= form_with(model: @food, url: food_path, local: true) do |form| %>
    <div class = "mt-4 p-2">
      <%= form.label :name, "Food Name:" %>
      <%= form.text_field :name,
          autofocus: true, 
          autocomplete: 'name', 
          placeholder: 'New food name', 
          class: 'form-control' 
      %>
      <% if @food.errors.any? %>
          <p class="text-danger mb-0">
            <%= @food.errors[:name].first %>
          </p>
      <% end %>
    </div>

    <div class = "mt-2 p-2">
      <%= form.label :measurement_unit, "Measurement Unit:" %>
      <%= form.text_field :measurement_unit,
          autofocus: true, 
          autocomplete: 'measurement unit', 
          placeholder: 'Measurement Unit', 
          class: 'form-control' 
      %>
      <% if @food.errors.any? %>
          <p class="text-danger mb-0">
            <%= @food.errors[:measurement_unit].first %>
          </p>
      <% end %>
    </div>

     <div class = "mt-2 p-2">
          <%= form.label :quantity, "Quantity:" %>
          <%= form.number_field :quantity,
              autofocus: true, 
              autocomplete: 'quantity', 
              placeholder: 'Quantity', 
              class: 'form-control' 
          %>
          <% if @food.errors.any? %>
              <p class="text-danger mb-0">
                <%= @food.errors[:quantity].first %>
              </p>
          <% end %>
        </div>

    <div class = "mt-2 p-2">
      <%= form.label :price, "Unit Price:" %>
      <%= form.number_field :price,
          autofocus: true,
          autocomplete: 'price',
          placeholder: 'Unit Price',
          class: 'form-control' 
      %>
      <% if @food.errors.any? %>
          <p class="text-danger mb-0">
            <%= @food.errors[:price].first %>
          </p>
      <% end %>
    </div>

    <div class="actions text-center">
      <%= form.submit class: 'btn btn-outline-dark btn-sm mt-4' %>
      <%= link_to 'Cancel', foods_path, class: 'btn btn-outline-dark btn-sm mt-4 px-3' %>
    </div>
 <% end %>

app/views/foods/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-4 p-2">
      <h1 class="text-center">Editing Food</h1>
        <%= render "form", food: @food %>
    </div>
  </div>
</div>

app/views/foods/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 mt-4 p-2">
      <h1 class="text-center">
        Foods List
      </h1>

      <div class="d-flex justify-content-end">
        <%= link_to 'New Food', new_food_path, class: "btn btn-primary" %>
      </div>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
        </p>
      <% elsif @foods.empty? %>
        <p class="alert alert-info">
        There are no foods in the database for the user. Please add new food.
        </p>
      <% end %>

      <% if @foods.any? %>
        <hr>
        <table class="table table-striped table-ligth">
          <thead>
            <tr>
              <th>#</th>
              <th>Food</th>
              <th>Measurement Unit</th>
              <th>Unit Price</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @foods.each_with_index do |food, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= food.name %></td>
                <td><%= food.measurement_unit %></td>
                <td><%= food.price %></td>
                <td class="d-flex justify-content-center justify-content-around" >
                  <span> <%= link_to "Modify", edit_food_path(food), class: "btn btn-danger"%> </span>
                  <span> <%= button_to "Remove", food_path(food), class: "btn btn-danger", method: :delete%></span>                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>     
</div>

app/views/foods/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-4 p-2">
      <h1 class="text-center">Add New Food</h1>
      <%= form_with(model: @food, url: foods_path, local: true) do |form| %>
        <div class = "mt-4 p-2">
          <%= form.label :name, "Food Name:" %>
          <%= form.text_field :name,
              autofocus: true, 
              autocomplete: 'name', 
              placeholder: 'New food name', 
              class: 'form-control' 
          %>
          <% if @food.errors.any? %>
              <p class="text-danger mb-0">
                <%= @food.errors[:name].first %>
              </p>
          <% end %>
        </div>
    
        <div class = "mt-2 p-2">
          <%= form.label :measurement_unit, "Measurement Unit:" %>
          <%= form.text_field :measurement_unit,
              autofocus: true, 
              autocomplete: 'measurement unit', 
              placeholder: 'Measurement Unit', 
              class: 'form-control' 
          %>
          <% if @food.errors.any? %>
              <p class="text-danger mb-0">
                <%= @food.errors[:measurement_unit].first %>
              </p>
          <% end %>
        </div>
    
        <div class = "mt-2 p-2">
          <%= form.label :quantity, "Quantity:" %>
          <%= form.number_field :quantity,
              autofocus: true, 
              autocomplete: 'quantity', 
              placeholder: 'Quantity', 
              class: 'form-control' 
          %>
          <% if @food.errors.any? %>
              <p class="text-danger mb-0">
                <%= @food.errors[:quantity].first %>
              </p>
          <% end %>
        </div>
    
        <div class = "mt-2 p-2">
          <%= form.label :price, "Unit Price:" %>
          <%= form.number_field :price,
              autofocus: true,
              autocomplete: 'price',
              placeholder: 'Unit Price',
              class: 'form-control' 
          %>
          <% if @food.errors.any? %>
              <p class="text-danger mb-0">
                <%= @food.errors[:price].first %>
              </p>
          <% end %>
        </div>
    
        <div class="actions text-center">
          <%= form.submit class: 'btn btn-outline-dark btn-sm mt-4' %>
          <%= link_to 'Cancel', foods_path, class: 'btn btn-outline-dark btn-sm mt-4 px-3' %>
        </div>
      <% end %>
    </div>
  </div>
</div>