config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'recipes#index'


resources :recipes, only: [:index, :show, :new, :update, :destroy, :create] do
  resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
end

resources :foods do
  resources :recipe_foods, only: %i[edit, update, new, create, index, destroy]
end

get 'general_shopping_list/:recipe_id', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

resources :recipe_food, only: %i[index show edit update destroy]
resources :public_recipes, only: %i[index show]

resources :shopping_list, only: %i[index show]
resources :general_shopping_list, only: %i[index show]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :recipe_id, presence: true, uniqueness: { scope: :food_id }
  validates :food_id, presence: true, uniqueness: { scope: :recipe_id }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(add_ingredients_params)
    @recipe_food.recipe_id = params[:recipe_id]
    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient added successfully.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        @recipe = Recipe.find(params[:recipe_id])
        @foods = Food.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: unprocessable_entity }
      end
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(@recipe_food.recipe_id)
    @foods = Food.all
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    id = @recipe_food.recipe_id
    respond_to do |format|
      if @recipe_food.update(add_ingredients_params)
        format.html { redirect_to recipe_path(id), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    id = @recipe_food.recipe_id

    respond_to do |format|
      if @recipe_food.destroy
        format.html { redirect_to recipe_path(id), notice: 'Food was successfully removed.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { redirect_to recipe_path(id), alert: 'You are not authorized to remove this food.' }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_ingredients_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
  def notice_message
    url = Rails.application.routes.recognize_path(request.referrer)
    flash.delete(:notice) unless %w[index show new edit update
                                    destroy].include?(url[:action]) && url[:controller] == 'recipes'
  end
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: @recipe_food, url: recipe_recipe_foods_path, local: true) do |form| %>
  <div class = "mt-4 p-2">
    <%= form.hidden_field :recipe_id, value: @recipe.id %>
    <%= form.collection_select :food_id, @foods, :id, :name, { prompt: '.. Select a Food ..' }, id: 'food-select'%>

    <% if @recipe_food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe_food.errors[:food_id].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.number_field :quantity,
        autofocus: true,
        autocomplete: 'quantity',
        placeholder: 'Enter quantity',
        class: 'form-control'
    %>
    <% if @recipe_food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe_food.errors[:quantity].first %>
        </p>
    <% end %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: 'btn btn-outline-dark btn-sm mt-4 px-3' %>
    <%= link_to 'Cancel', recipe_path(@recipe), class: "btn btn-outline-dark btn-sm mt-4 px-3" %>
  </div>
<% end %>

app/views/recipe_foods/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-4 p-2">
      <h1 class="text-center">
          Edit Ingredient for Recipe
        </h1>

      <%= form_with(model: @recipe_food, url: recipe_recipe_food_path, local: true) do |form| %>
        <div class = "mt-4 p-2">
          <%= form.hidden_field :recipe_id, value: @recipe.id %>
          <%= form.collection_select :food_id, @foods, :id, :name, { prompt: '.. Select a Food ..' }, id: 'food-select'%>
          
          <% if @recipe_food.errors.any? %>
            <p class="text-danger mb-0">
              <%= @recipe_food.errors[:food_id].first %>
            </p>
          <% end %>
        </div>
      
        <div class = "mt-2 p-2">
          <%= form.number_field :quantity,
            autofocus: true,
            autocomplete: 'quantity',
            placeholder: 'Quantity in grams',
            class: 'form-control'
          %>
          <% if @recipe_food.errors.any? %>
            <p class="text-danger mb-0">
              <%= @recipe_food.errors[:quantity].first %>
            </p>
          <% end %>
        </div>
      
        <div class="actions text-center">
          <%= form.submit class: 'btn btn-outline-dark btn-sm mt-4 px-3' %>
          <%= link_to 'Cancel', recipe_path(@recipe), class: "btn btn-outline-dark btn-sm mt-4 px-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-4 p-2">
      <h1 class="text-center">
          Add Ingredient to
          <%= @recipe.name %>
        </h1>
      <%= render 'form' %>
    </div>
  </div>
</div>